version: "3"

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: nextjs-boilerplate:latest
    ports:
      - "3001:3000"
