version: "3"

services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: nextjs-boilerplate:latest
    ports:
      - "3003:3000"
