import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

// FIXME: change the metadata to match your project
// opengraph images should be 1200x630
export const metadata: Metadata = {
  title: "GrowsIT Next.js Starter",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    locale: "th_TH",
    description:
      "GrowsIT Next.js Boilerplate Please change this description to your own",
    images:
      "https://carfinn-s3-dev.s3.ap-southeast-1.amazonaws.com/car/customer_document/pf17188544540.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
